### ISSUE TITLE
Improve documentation of the serverless curriculum

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/BitCamp#1]
Currently, the README.md files for each of the weeks, as well as the one for the main repository does not provide enough context. Please add gifs/screenshots of the projects, more detailed descriptions, and links to videos (if exists).

**Comment by emsesc** [comment]
Added descriptions and gifs to all README.md files for more context. Concise summaries aim to clarify what each week's purposes and goals are for those who want to contribute to the open-source curriculum. (README file was also added to Final Projects/ to introduce the bitproject final project process)

**Comment by lazyplatypus** [comment]
Heyo don't close issues unless the PR is merged :)
