### ISSUE TITLE
[BUG] Intro to Serverless Week 3 Issue 4

### ISSUE THREAD

**Issue by shreythecray** [bitprj/BitCamp#152]
**Describe the bug**
1. onChange -> onchange (typo)
2. add descriptions for all elements and types in html/css part (https://github.com/shreythecray/bit-camp-learning-lab-test/issues/4#issue-799989401)
3. lines of <script> code need more context
4. LiveServer part - clarify that they might need to quit VS Code and reopen it if it doesn't show up after installation
5. Add a new issue or instruction in week 3 to work on the html
6. Around checkpoint 4 and 5, we need to explain how to fix CORS policy issue through Azure portal

**Context**
Week 3 issue 4

**Desired Outcome**
Will be making PR for this today

**Comment by shreythecray** [comment]
@emsesc should we have the students actually develop their html more?

**Comment by emsesc** [comment]
@shreythecray By developing html more do you mean adding more components or making it look pretty :)
