### ISSUE TITLE
Improve Overview of Slack Bitcamp

### ISSUE THREAD

**Issue by emsesc** [bitprj/BitCamp#22]
Currently, the root md file documentation for Bitcamp Slack is detailed but not yet friendly for new open-source contributors unfamiliar with the camp. Split the "Overview:" into sections similar to that of the [Serverless Bitcamp](https://github.com/bitprj/BitCamp/tree/master/Serverless-Functions). This will clarify to contributors what tools the camp utilizes, what the objectives are, and what students will learn in a more readable format.

**Comment by beaubhp** [comment]
Will do. Finalizing the code and learning lab content hopefully by tomorrow and then will figure out the READMEs @emsesc.
