### ISSUE TITLE
BitCamp/Serverless-Functions/README.md

### ISSUE THREAD

**Issue by etrunk** [bitprj/BitCamp#4]
Can a complete beginner who doesn't know anything about html, css, js do this? Are there any steps that should be taken before starting the camp? This is usually a good place to put prerequisites. Instructions for setting up, if any, can be put here or put as an assignment if that's too much for this README.

**Comment by etrunk** [comment]
Fix weekly learning objective. Week 1 looks like week0/ and week1/, but we're learning js before setting up?

**Comment by emsesc** [comment]
Prerequisites were added to Week 0 + weekly objectives were modified in week0/ and week1/
