### ISSUE TITLE
[BUG] Readme.md refresh

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/BitCamp#85]
**Describe the bug**
The readme is missing key elements
- summary of each of the folders
- contributing blurb and link to the markdown file
- reporting bugs (short blurb + link)

**Context**
main root folder readme. 

**Desired Outcome**
add missing elements

**Comment by lazyplatypus** [comment]
https://github.com/freeCodeCamp/freeCodeCamp reference

**Comment by emsesc** [comment]
@lazyplatypus by "folders" do you mean that each camp should also be introduced?
